SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID
;


# 박서연 -- 3월 태어난 사람, 여성이라는 특성을 가지고 작성. 
# DATE_OF_BIRTH 를 그대로 출력하면 분,시,초가 그대로 나오기에 전처리
